/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus dependency visibility.
         *
         *     Reports "not_configured" rather than failing when Postgres/Redis are
         *     absent, so the service is deployable and inspectable before the queue and
         *     database exist.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Analysis
         * @description Queue an analysis, or hand back the existing one.
         *
         *     Returns **200** with the existing run when this ticker/date/profile has
         *     already been analysed, and **202** when a new job was queued. Callers can
         *     treat both as success; the status code tells them whether they paid for a
         *     run. Serving repeats from cache is what makes on-demand analysis
         *     affordable for a public audience, and it also means two users asking the
         *     same question get the same answer rather than two independently sampled
         *     verdicts.
         */
        post: operations["request_analysis_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Ask a queued or running analysis to stop.
         *
         *     Cooperative, not instant, for a running analysis: the worker checks a
         *     flag once per streamed chunk (see RunEventWriter.should_stop() and
         *     propagate_streaming's loop), typically within about one token's
         *     latency but never mid-way through an LLM call already in flight. A
         *     still-queued run (no worker has claimed it yet) is cancelled outright.
         *
         *     404 covers both "no such run" and "this run already finished" — the
         *     caller cannot stop what is not running either way, and doesn't need to
         *     distinguish the two to know that.
         */
        post: operations["stop_run_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{ticker}/{analysis_date}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run History
         * @description Every analysis of one question, so repeat runs can be compared.
         *
         *     This is what backs a "you have run this 3 times, and they disagreed" view.
         *     Hiding that would be the dishonest option — the runs read identical data,
         *     so a split is real information about how balanced the evidence is.
         */
        get: operations["get_run_history_runs__ticker___analysis_date__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Poll a run. Carries reports only once status is ``completed``.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run
         * @description Server-Sent Events: token-level live view of an in-progress run.
         *
         *     Honors Last-Event-ID (sent automatically by a reconnecting browser
         *     EventSource) so a refresh mid-run resumes rather than replaying from
         *     the start. Polls run_events via the same WAL-mode SQLite pattern
         *     api/db.py already documents for concurrent reader/writer access.
         *
         *     Registered ABOVE /runs/{ticker}/{analysis_date} on purpose: both are
         *     two-segment paths under /runs, and FastAPI matches route order, so this
         *     one must come first or every "stream" would be swallowed as a bogus
         *     analysis_date and 422 instead of streaming.
         */
        get: operations["stream_run_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{ticker}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run By Ticker
         * @description Fetch a completed analysis by what it is *about* rather than by job id.
         *
         *     This is the endpoint a UI actually uses on a stock page: it does not know
         *     a run id, only which company and day the user is looking at.
         */
        get: operations["get_run_by_ticker_runs__ticker___analysis_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisProfile
         * @description Maps to the engine's config profiles.
         *
         *     ``fast`` is get_fast_config(): analysts run concurrently, 1 debate round,
         *     balanced report length — and it fetches exactly the same data as
         *     ``detailed``. See tradingagents/default_config.py.
         * @enum {string}
         */
        AnalysisProfile: "fast" | "detailed";
        /** AnalysisRequest */
        AnalysisRequest: {
            /**
             * Ticker
             * @description NSE/BSE symbol. A bare name like 'RELIANCE' is resolved to 'RELIANCE.NS' by the engine.
             * @example SIEMENS.NS
             * @example RELIANCE
             */
            ticker: string;
            /**
             * Analysis Date
             * @description Defaults to today. Also the cache key: a repeat request for the same ticker and date returns the existing run instead of spending a new one.
             */
            analysis_date?: string | null;
            /** @default fast */
            profile: components["schemas"]["AnalysisProfile"];
            /**
             * Force
             * @description Run a fresh analysis even when one already exists for this ticker and date. The existing run is kept — results accumulate rather than being overwritten, so they can be compared.
             * @default false
             */
            force: boolean;
            /**
             * Refresh Data
             * @description Also re-fetch news, filings and social data instead of replaying the day's snapshot. Implies force. Use when something has actually happened since the last run; leave false to re-reason over identical inputs.
             * @default false
             */
            refresh_data: boolean;
            /**
             * Time Horizon
             * @description Optional investor holding-period guidance for the Portfolio Manager, e.g. '3-6 months'. Steers how the rating and price target are framed; does not change what data the analysts see, and the Portfolio Manager will say so rather than force a verdict if the evidence points to a different horizon. Implies force, so a request with a horizon never silently reuses a run cached for a different (or no) horizon.
             * @example 3-6 months
             */
            time_horizon?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            /** Queue */
            queue: string;
        };
        /**
         * NewsSource
         * @description One article the News or Sentiment report was actually given.
         *
         *     Recovered from the pre-fetched article text those reports already
         *     embed verbatim — never a claim about which sentence in the report
         *     cites it, just "this was in the grounding set."
         */
        NewsSource: {
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Published Date */
            published_date?: string | null;
            /** Url */
            url?: string | null;
            /** Snippet */
            snippet?: string | null;
        };
        /**
         * Reports
         * @description The full analysis text, stage by stage.
         *
         *     This is the substance of the product: a research tool surfaces the
         *     evidence and both sides of the argument, not just a rating. Every field is
         *     optional because a caller may deselect analysts.
         */
        Reports: {
            /** Market */
            market?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** News */
            news?: string | null;
            /** Fundamentals */
            fundamentals?: string | null;
            /** Bull Case */
            bull_case?: string | null;
            /** Bear Case */
            bear_case?: string | null;
            /** Investment Plan */
            investment_plan?: string | null;
            /** Trader Plan */
            trader_plan?: string | null;
            /** Risk Debate */
            risk_debate?: string | null;
            /** Final Decision */
            final_decision?: string | null;
        };
        /**
         * RunAccepted
         * @description 202 body for a newly queued run.
         */
        RunAccepted: {
            /** Id */
            id: string;
            status: components["schemas"]["RunStatus"];
            /** Poll Url */
            poll_url: string;
            /**
             * Estimated Seconds
             * @description Rough guide for the client's progress UI, not a promise.
             */
            estimated_seconds: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            profile: components["schemas"]["AnalysisProfile"];
            status: components["schemas"]["RunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Cached
             * @description True when served from an existing run rather than a new analysis. Repeat requests for the same ticker and date are free.
             * @default false
             */
            cached: boolean;
            verdict?: components["schemas"]["Verdict"] | null;
            reports?: components["schemas"]["Reports"] | null;
            /**
             * Requested Time Horizon
             * @description The holding-period guidance the caller supplied, if any. Compare against verdict.time_horizon: the Portfolio Manager may state a different one when the evidence disagrees.
             */
            requested_time_horizon?: string | null;
            /**
             * News Sources
             * @description Articles the News/Sentiment reports were grounded in. Always a list — empty means nothing parsed, not an error.
             */
            news_sources?: components["schemas"]["NewsSource"][];
            /**
             * Run Count
             * @description How many analyses exist for this ticker, date and profile. Greater than 1 means someone requested a fresh run.
             * @default 1
             */
            run_count: number;
            /**
             * Verdict Is Contested
             * @description True when repeat runs of this same question reached DIFFERENT ratings. The inputs are identical by construction (the day's data is snapshotted), so disagreement means the evidence is genuinely balanced — that is information for the reader, not a bug to hide.
             * @default false
             */
            verdict_is_contested: boolean;
        };
        /**
         * RunHistory
         * @description Every analysis for one ticker/date/profile, newest first.
         */
        RunHistory: {
            /** Ticker */
            ticker: string;
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            profile: components["schemas"]["AnalysisProfile"];
            /** Run Count */
            run_count: number;
            /**
             * Ratings
             * @description Rating from each completed run, newest first.
             */
            ratings: (string | null)[];
            /** Verdict Is Contested */
            verdict_is_contested: boolean;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /**
         * RunSummary
         * @description Lightweight view — list endpoints and poll responses use this.
         */
        RunSummary: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            profile: components["schemas"]["AnalysisProfile"];
            status: components["schemas"]["RunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Cached
             * @description True when served from an existing run rather than a new analysis. Repeat requests for the same ticker and date are free.
             * @default false
             */
            cached: boolean;
        };
        /**
         * TradeLevels
         * @description Execution levels from the trader stage.
         *
         *     THE BOOK IS LONG-ONLY: ``stop_loss`` always sits BELOW ``entry_price``,
         *     for every action including Sell — where it guards the retained position
         *     rather than a short. Either field may be null; the engine drops a stop it
         *     cannot make coherent rather than emitting a misleading number.
         */
        TradeLevels: {
            /**
             * Action
             * @description Buy / Hold / Sell
             */
            action?: string | null;
            /** Entry Price */
            entry_price?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Position Sizing */
            position_sizing?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            /**
             * Rating
             * @description Buy / Overweight / Hold / Underweight / Sell
             */
            rating?: string | null;
            /** Price Target */
            price_target?: number | null;
            /** Time Horizon */
            time_horizon?: string | null;
            levels?: components["schemas"]["TradeLevels"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    request_analysis_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_history_runs__ticker___analysis_date__history_get: {
        parameters: {
            query?: {
                profile?: components["schemas"]["AnalysisProfile"];
            };
            header?: never;
            path: {
                ticker: string;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_by_ticker_runs__ticker___analysis_date__get: {
        parameters: {
            query?: {
                profile?: components["schemas"]["AnalysisProfile"];
            };
            header?: never;
            path: {
                ticker: string;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
